### PR TITLE
feat: container and vendor

### PR DESCRIPTION
**Pull request by jonathanmorais**
first structure for use with docker.

### CODE REVIEW

**Comment by brunopadz** [comment]
cc: @vidalvasconcelos

**Comment by vidalvasconcelos** [comment]
@jonathanmorais  I assume you accidentally commit the project's dependencies. How these files can be downloaded using the command `go get ./` you can remove these files.

**Comment by brunopadz** [comment]
Hi @jonathanmorais, could you please be more specific why you're implementing this? 
I understand you're containerizing it, but doesn't it make more sense to create a docker image as a release?

**Comment by brunopadz** [comment]
hey @jonathanmorais, any news on your work?

**Pull request closed without merging**
